<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <title>ADJS: Promise</title>
</head>
<body>

    
    <script>
        // let complete = false;

        // let pro = new Promise(function (resolve,reject) {
        //     if(complete){
        //         resolve("I am successful.");
        //     }else{
        //         reject("I am failed.");
        //     }
        // });


//         function pro(complete) {
//             return new Promise(function (resolve,reject) {
//                 console.log("Fetching data, please wait...");
//             setTimeout(()=>{
//                  if(complete){
//                     resolve("I am successful");
//                 }else{
//                     reject("I am failed");
//                 }
//             },2000)

               
//             })
//         }

//         let onfulfilment = (result) => {
//             console.log(result);
//         }

//         let onrejection = (error) =>{
//             console.log(error);
//         }
        
// pro(false).then(onfulfilment).catch(onrejection);


// function ankit(a,b) {
//     return new Promise(function (resolve,reject) {
//         console.log("Your data is under process. please wait...");
//         var c = a/b;
//         setTimeout(()=>{
//             if(c){
//                 resolve(`Your answer : ${c}`);
//             }else{
//                 reject("Failed to calculate.");
//             }
//         },2000)
//     })
    
// }

// let fullfilment = (result)=>{
//     console.log(result);
// }

// let rejection = (error)=>{
//     console.log(error);
// }


// ankit(5,3).then(fullfilment).catch(rejection);
    
// function pro() {
//     return new Promise(function (resolve,reject) {
//         console.log("Fetching data, please wait...");
//         setTimeout(()=>{
//             $.get("https://jsonplaceholder.typicode.com/posts",function(data) {
//                 console.log(data);
//             }).fail(err=>{
//                 reject("Fail to load JSON.")
//             })
//         },2000)
//     })
    
// }



// pro().then((result)=>{
//     console.log(result);
// }).catch((error)=>{
//     console.log(error);
// });
    

// let p1 = new Promise(function (resolve,reject) {
//     setTimeout(()=>{
//         console.log("First promise has resolved.");
//         resolve(50);
//     },2*1000)
// })

// let p2 = new Promise(function (resolve,reject) {
//     setTimeout(()=>{
//         console.log("Second promise has resolved.");
//         reject(100);
//     },4*1000)
// });

// let p3 = new Promise(function (resolve,reject) {
//     setTimeout(()=>{
//         console.log("Third promise has resolved.");
//         resolve(150);
//     },6*1000)
// });
// var total = 0;


// Promise.all([p1,p2,p3]).then((result)=>{
//     for(var i in result) {total += result[i];}
//     console.log(`Result: ${result}`);
//     console.log(`Total: ${total}`);
// }).catch((error)=>{
//     console.log(`Error: ${error}`);
// })

let promiseCall = function (returnData, message) {
    return function (resolve,reject) {
        
        setTimeout(() => {
            console.log(`${message} promise has resolved`);
            resolve(returnData);
        }, returnData*10);
    }
}




let p1 = new Promise(promiseCall(50,"First"));
let p2 = new Promise(promiseCall(100,"Second"));
let p3 = new Promise(promiseCall(150,"Third"));
let p4 = new Promise(function (resolve,reject) {
    resolve("The 4th Promise has rejected.")
})

var total = 0;


Promise.all([p1,p2,p3,p4]).then((result)=>{
    for(var i in result) {total += result[i];}
    console.log(`Result: ${result}`);
    console.log(`Total: ${total}`);
}).catch((error)=>{
    console.log(`Error: ${error}`);
})

    </script>
    
</body>
</html>